minerals/urls.py
from django.urls import path


from . import views


app_name = 'minerals'
urlpatterns = [
    path('', views.mineral_list, name='index'),
    path('<int:pk>/', views.mineral_detail, name='detail'),
    path('random_mineral', views.random_mineral, name='random_mineral'),
]

project6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('minerals/', include('minerals.urls')),
    path('admin/', admin.site.urls),
]

minerals/models.py
from django.db import models


class Mineral(models.Model):
    name = models.CharField(max_length=255)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    group = models.CharField(max_length=255)

    specific_gravity = models.CharField(blank=True, max_length=255)
    crystal_habit = models.CharField(blank=True, max_length=255)
    crystal_system = models.CharField(blank=True, max_length=255)
    strunz_classification = models.CharField(blank=True, max_length=255)
    unit_cell = models.CharField(blank=True, max_length=255)
    color = models.CharField(blank=True, max_length=255)
    crystal_symmetry = models.CharField(blank=True, max_length=255)
    cleavage = models.CharField(blank=True, max_length=255)
    mohs_scale_hardness = models.CharField(blank=True, max_length=255)
    luster = models.CharField(blank=True, max_length=255)
    streak = models.CharField(blank=True, max_length=255)
    diaphaneity = models.CharField(blank=True, max_length=255)
    optical_properties = models.CharField(blank=True, max_length=255)
    refractive_index = models.CharField(blank=True, max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name',]

minerals/views.py
import random

from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Mineral


# Create your views here.

def mineral_list(request):
    minerals = Mineral.objects.all()
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals})


def mineral_detail(request, pk):
    mineral = get_object_or_404(Mineral, pk=pk)
    attributes = vars(mineral)
    filter_attr = ['id', '_state', 'name', 'image_filename',
                   'image_caption', 'category', 'formula',
                   'strunz_classification']
    res = map(lambda x: (x[0].replace("_", " "), x[1]),
              filter(
                  lambda x: x[0] not in filter_attr and x[1], attributes.items()))
    attr = dict(res)
    return render(request, 'minerals/mineral_detail.html',
                  {'mineral': mineral, 'attr': attr})


def random_mineral(request):
    count = Mineral.objects.count()
    picked = random.randint(1,count)
    return mineral_detail(request, picked)



# class IndexView(generic.ListView):
#     template_name = 'minerals/index.html'
#     context_object_name = 'minerals'
#
#     def get_queryset(self):
#         """Returns all the minerals"""
#         return Mineral.objects.all()


# class DetailView(generic.DetailView):
#     model = Mineral
#
#     def get_context_data(self, **kwargs):
#         context = super(DetailView, self).get_context_data(**kwargs)
#         # print(context)
#         attributes = vars(context['mineral'])
#         filter_attr = ['id', '_state', 'name', 'image_filename',
#                        'image_caption']
#         res = map(lambda x: (x[0].replace("_", " ").title(),x[1]),
#                   filter(
#                       lambda x: x[0] not in filter_attr and x[1], attributes.items()))
#         context['attr'] = dict(res)
#
#         print(context['attr'])
#         return context

minerals/templates/minerals/mineral_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<div class="grid-100 mineral__container">
    <h1 class="mineral__name">{{ mineral.name }}</h1>
    <div class="mineral__image-bg">
            <img class="mineral__image" src="{% static 'images/' %}{{ mineral.image_filename }}">
            <p class="mineral__caption">{{  mineral.image_caption }}</p>
    </div>
    <div class="mineral__table-container">
        <table class="mineral__table">
            <tr>
                <td class="mineral__category">Category</td>
                <td>{{ mineral.category }}</td>
            </tr>
            <tr>
                <td class="mineral__category">Formula</td>
                <td class="mineral__formula">{{ mineral.formula }}</td>
            </tr>
            <tr>
              <td class="mineral__category">Strunz Classification</td>
              <td>{{ mineral.strunz_classification }}</td>
            </tr>
        {% for key,value in attr.items %}
            <tr>
                <td class="mineral__category">{{ key.title }}</td>
                <td class="mineral__formula">{{ value }}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

minerals/templates/minerals/mineral_list.html
{%  extends 'layout.html' %}


{% block content %}
    <div class="grid-100">
    <ul class="minerals__container">
        {%  for mineral in minerals %}
            <li class="minerals__item">
                <a class="minerals__anchor" href="{%  url 'minerals:detail' mineral.id %}">
                    {{ mineral.name|truncatechars:"22" }}</a>
            </li>
        {% endfor %}
    </ul>
    </div>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Serhat's Minerals: A magnificant catalog of minerals</title>
  <meta name="description" content="Minerals catalog">
  <meta name="author" content="Serhat Bolsu">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'minerals/global.css' %}">
</head>
<body>
  <div class="bounds">
    <div class="grid-100">
      <a href="{% url 'minerals:index' %}">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Serhat's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
    {% block content %}{% endblock %}
  </div>
  <div class="minerals__random">
    <a class="minerals__anchor" href="{%  url 'minerals:index' %}">Return to List of Minerals</a>
    <a class="minerals__anchor" href="{%  url 'minerals:random_mineral' %}">Show random mineral</a>
  </div>
</body>
</html>